In [3]:
import pickle
import os
import sys
# Add the folder containing the Python files to the Python path
sys.path.append('CM_train')
sys.path.append('CM_auxiliary')
sys.path.append('CM_logging')
import mir_eval
from copy import deepcopy
import numpy as np

In [4]:
with open('trained_idioms/BachChorales.pickle', 'rb') as f:
    bc = pickle.load(f)

In [5]:
print(bc.__dict__)

{'name': 'BachChorales', 'modes': {'[0 2 3 5 7 8 10]': <CM_TR_TrainingIdiom_class.TrainingMode object at 0x79a3549bc750>, '[0 2 4 5 7 9 11]': <CM_TR_TrainingIdiom_class.TrainingMode object at 0x79a313deaa10>}}


In [6]:
modes = bc.modes
print(modes)

{'[0 2 3 5 7 8 10]': <CM_TR_TrainingIdiom_class.TrainingMode object at 0x79a3549bc750>, '[0 2 4 5 7 9 11]': <CM_TR_TrainingIdiom_class.TrainingMode object at 0x79a313deaa10>}


In [7]:
mode_0 = modes[list(modes.keys())[0]]
print(mode_0.__dict__)

{'mode': array([ 0,  2,  3,  5,  7,  8, 10]), 'mode_pcp': array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0]), 'mode_name': '[0 2 3 5 7 8 10]', 'idiom_name': 'BachChorales', 'gct_info': <CM_TR_TrainingIdiom_class.GCT_info object at 0x79a35d724110>, 'gct_group_info': <CM_TR_TrainingIdiom_class.GCT_info object at 0x79a313d9ef10>, 'cadences': {'intermediate': <CM_TR_TrainingIdiom_class.TrainingCadences object at 0x79a313dbc210>, 'final': <CM_TR_TrainingIdiom_class.TrainingCadences object at 0x79a313de8650>}}


In [8]:
gct_info_0 = mode_0.gct_info
print(gct_info_0.__dict__.keys())

dict_keys(['gcts_array', 'gcts_counter', 'gct_group_structures', 'gcts_membership_dictionary', 'gcts_labels', 'gcts_relative_pcs', 'gcts_occurances', 'gcts_probabilities', 'gcts_initial_array', 'gcts_initial_counter', 'gcts_initial_probabilities', 'gcts_transitions_sum', 'gcts_markov', 'gct_vl_phrases', 'gct_vl_dict', 'gct_vl'])


In [9]:
print(gct_info_0.gcts_labels)
print(len(gct_info_0.gcts_relative_pcs))
print(gct_info_0.gcts_relative_pcs[0])
print(gct_info_0.gcts_markov.shape)
print(gct_info_0.gcts_probabilities)
rpcs = gct_info_0.gcts_relative_pcs
probs = gct_info_0.gcts_probabilities
tr = gct_info_0.gcts_markov

['[0 0 3 7]', '[7 0 4 7]', '[10 0 4 7]', '[3 0 4 7]', '[2 0 3 9]', '[5 0 3 7 9]', '[0 0 4 7]', '[8 0 4 7]', '[5 0 3 7]', '[2 0 4 7 10]', '[7 0 4 7 10]', '[0 0 3]', '[5 0 3 6 9]', '[5 0 4 7 10]', '[5 0 4 7]', '[2 0 4 7]', '[7 0 3 7]', '[10 0 4 7 10]', '[7 0 4]', '[2 0 3 6]', '[8 0 4 7 9]', '[3 0 4 7 9]', '[0 0 4 7 10]', '[7 0 4 10]', '[0 0 3 7 8]', '[0 0 3 6 9]', '[10 0 7]', '[5 0 4 10]', '[3 0 4]', '[10 0 4 7 9]', '[9 0 3 9]', '[0 0 3 9]', '[0 0 7]', '[5 0 4 7 9]', '[11 0 3 9]', '[2 0 3 7]', '[7 0 4 8]', '[7 0 3 9]', '[7 0 3 6 9]']
39
[1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
(39, 39)
[0.27967807 0.17102616 0.02615694 0.04828974 0.03018109 0.04024145
 0.03420523 0.04828974 0.03822938 0.01006036 0.07042254 0.00804829
 0.02012072 0.01207243 0.03219316 0.01006036 0.01810865 0.00402414
 0.00402414 0.02615694 0.00603622 0.00402414 0.00603622 0.00603622
 0.00201207 0.00804829 0.00402414 0.00201207 0.00402414 0.00201207
 0.00402414 0.00201207 0.00402414 0.00201207 0.00201207 0.00402414
 0.0020120

In [10]:
MIR_QUALITIES = mir_eval.chord.QUALITIES
EXT_MIR_QUALITIES = deepcopy( MIR_QUALITIES )
for k in list(MIR_QUALITIES.keys()) + ['7(b9)', '7(#9)', '7(#11)', '7(b13)']:
    _, semitone_bitmap, _ = mir_eval.chord.encode( 'C' + (len(k) > 0)*':' + k, reduce_extended_chords=True )
    EXT_MIR_QUALITIES[k] = semitone_bitmap

In [11]:
INT_TO_ROOT_SHARP = {
    0: 'C',
    1: 'C#',
    2: 'D',
    3: 'D#',
    4: 'E',
    5: 'F',
    6: 'F#',
    7: 'G',
    8: 'G#',
    9: 'A',
    10: 'A#',
    11: 'B',
}
ROOT_TO_INT_SHARP = {v:k for k, v in INT_TO_ROOT_SHARP.items()}

In [12]:
print(ROOT_TO_INT_SHARP)

{'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5, 'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}


In [13]:
all_chords = {}

In [14]:
for r_str, r_int in ROOT_TO_INT_SHARP.items():
    for type_str, type_array in EXT_MIR_QUALITIES.items():
        all_chords[ r_str + (len(type_str)>0)*':' + type_str] = np.roll( type_array, r_int )

In [15]:
print(all_chords['D:maj'])

[0 0 1 0 0 0 1 0 0 1 0 0]


In [16]:
print(len(all_chords))

348


In [17]:
mir_rpcs = tuple( all_chords.values() )
mir_symbols = tuple( all_chords.keys() )

In [18]:
print(mir_rpcs)
print(mir_symbols)

(array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]), array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]), array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]), array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]), array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]), array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]), array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]), array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1]), array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0]), array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1]), array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]), array([1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0]), array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]), array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1]), array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0]), array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1]), array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0]), array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0]), array([1,

In [19]:
# keep all mir_eval pcps in a matrix to speed-up match making
all_mir_eval_pcps = np.zeros( (len(all_chords), 12) )
for i,v in enumerate(all_chords.values()):
    all_mir_eval_pcps[i, :] = v

In [20]:
rpc = rpcs[0]

In [21]:
# translate transition matrix of idiom to mir_eval-compatible transition matrix
# for each chord in rpcs, find the closes mir_eval rpc
matches = {}
for i, (rpc, rpc_prob) in enumerate( zip(rpcs, probs) ):
    tmp_all_matches = []
    max_match = -1
    max_idx = -1
    for j, (m_rpc, m_symbol) in enumerate( zip(mir_rpcs, mir_symbols) ):
        tmp_match = np.sum( m_rpc == rpc )
        tmp_all_matches.append(tmp_match)
        if max_match < tmp_match:
            max_match = tmp_match
            max_idx = j
    matches[i] = {
        'rpc': rpc,
        'prob': rpc_prob,
        'match_idx': max_idx,
        'match_rpc': mir_rpcs[max_idx],
        'match_symbol': mir_symbols[max_idx],
        'all_match_values': tmp_all_matches
    }

In [22]:
# map matches to transition matrix
mir_transitions = np.zeros( (len(all_chords), len(all_chords)) )
print(mir_transitions.shape)

(348, 348)


In [23]:
print(tr.shape)
print(len(matches))
print(matches[0]['match_idx'])

(39, 39)
39
1


In [24]:
for i, (i_k, i_v) in enumerate(matches.items()):
    for j, (j_k, j_v) in enumerate(matches.items()):
        mir_transitions[ i_v['match_idx'] , j_v['match_idx'] ] = tr[i,j]

In [25]:
np.savetxt( 'debug/tr.txt', tr )
np.savetxt( 'debug/mir_transitions.txt', mir_transitions )

In [26]:
print(matches[8])

{'rpc': array([1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.]), 'prob': 0.03822937625754527, 'match_idx': 146, 'match_rpc': array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]), 'match_symbol': 'F:min', 'all_match_values': [8, 8, 10, 8, 10, 8, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 7, 7, 6, 6, 6, 10, 9, 8, 6, 6, 6, 8, 10, 8, 8, 6, 8, 8, 9, 11, 7, 9, 9, 7, 5, 5, 10, 6, 8, 5, 7, 8, 4, 6, 8, 9, 10, 8, 8, 8, 8, 6, 8, 6, 10, 6, 6, 7, 5, 9, 7, 5, 7, 9, 11, 4, 8, 6, 7, 5, 2, 6, 4, 8, 7, 6, 6, 8, 8, 6, 6, 6, 6, 6, 8, 8, 5, 5, 5, 5, 7, 7, 7, 5, 6, 6, 6, 7, 7, 8, 8, 8, 8, 7, 6, 4, 4, 4, 4, 8, 6, 10, 6, 6, 6, 7, 7, 5, 5, 7, 5, 5, 5, 6, 4, 6, 3, 5, 4, 2, 4, 8, 7, 8, 8, 6, 6, 8, 10, 12, 8, 10, 10, 10, 9, 9, 11, 11, 9, 11, 9, 9, 8, 10, 8, 9, 7, 6, 8, 6, 10, 11, 10, 8, 10, 8, 8, 6, 6, 6, 8, 6, 8, 5, 7, 5, 7, 5, 5, 7, 7, 8, 6, 6, 5, 5, 6, 4, 4, 8, 7, 6, 4, 4, 6, 4, 6, 6, 6, 6, 8, 6, 7, 5, 7, 5, 5, 5, 5, 7, 4, 6, 6, 7, 7, 4, 6, 6, 8, 7, 6, 8, 6, 6, 6, 10, 8, 10, 8, 8, 8, 9, 9, 7, 7, 11, 9, 9, 7, 8, 6, 8, 5, 7, 8, 6,

In [27]:
# get idiom names
idiom_files = [fname for fname in os.listdir('trained_idioms') if not fname.startswith('.')]
print(idiom_files)

['organum.pickle', 'Jazz.pickle', 'Hindemith.pickle', 'beatles.pickle', 'fauxbourdon.pickle', 'BachChorales.pickle', 'modalChorales.pickle']


In [28]:
idioms = {}
# for each idiom
for idiom_file in idiom_files:
    with open( os.path.join('trained_idioms', idiom_file), 'rb') as f:
        idiom = pickle.load(f)
    idiom_name = idiom_file.split('.')[0]
    # initialize idiom by name
    idioms[idiom_name] = {}
    print(idiom_name)
    # get mode keys as list
    mode_keys = list(idiom.modes.keys())
    # for each mode
    for mode_key in mode_keys:
        idioms[idiom_name][mode_key] = {}
        # get mode object
        mode = idiom.modes[mode_key]
        # check if mode has minor third
        mode_is_minor = 3 in mode.mode
        print(mode_is_minor, mode.mode)
        idioms[idiom_name][mode_key]['is_minor'] = mode_is_minor
        idioms[idiom_name][mode_key]['mode_rpcs'] = mode.mode
        # get gct info
        gct_info = mode.gct_info
        # get all necessary information
        rpcs = gct_info.gcts_relative_pcs
        probs = gct_info.gcts_probabilities
        gcts_arrays = gct_info.gcts_array
        tr = gct_info.gcts_markov
        # find matches between chords of the idiom and mir_eval chords
        matches = {}
        for i, (rpc, rpc_prob) in enumerate( zip(rpcs, probs) ):
            tmp_all_matches = []
            max_match = -1
            max_idx = -1
            for j, (m_rpc, m_symbol) in enumerate( zip(mir_rpcs, mir_symbols) ):
                tmp_match = np.sum( m_rpc == np.roll(rpc, 9*mode_is_minor) )
                tmp_all_matches.append(tmp_match)
                if max_match < tmp_match:
                    max_match = tmp_match
                    max_idx = j
            matches[i] = {
                'rpc': rpc,
                'prob': rpc_prob,
                'gct_array': gcts_arrays[i],
                'match_idx': max_idx,
                'match_rpc': mir_rpcs[max_idx],
                'match_symbol': mir_symbols[max_idx],
                # 'all_match_values': tmp_all_matches
            }
        # store matches for debugging
        idioms[idiom_name][mode_key]['chords'] = matches
        # now that matches are found, map idiom transitions to mir_transitions
        # initialize mir_transitions
        mir_transitions = np.zeros( (len(all_chords), len(all_chords)) )
        # map matrices
        for i, (i_k, i_v) in enumerate(matches.items()):
            for j, (j_k, j_v) in enumerate(matches.items()):
                mir_transitions[ i_v['match_idx'] , j_v['match_idx'] ] = tr[i,j]
        # store information to idiom mode
        idioms[idiom_name][mode_key]['gct_transitions'] = tr
        idioms[idiom_name][mode_key]['mir_eval_transitions'] = mir_transitions

organum
True [ 0  2  3  5  7  8 10]
Jazz
True [ 0  2  3  5  7  8 10]
False [ 0  2  4  5  7  9 11]
False [ 0  2  4  5  7  9 10]
True [ 0  1  3  5  7  9 10]
True [ 0  2  3  5  7  9 10]
False [ 0  2  4  6  7  9 11]
Hindemith
False [ 0  2  4  5  7  9 11]
True [ 0  2  3  5  7  8 10]
False [ 0  2  4  5  7  9 10]
False [ 0  2  4  6  7  9 11]
beatles
True [ 0  2  3  5  7  8 10]
False [ 0  2  4  5  7  9 11]
fauxbourdon
False [ 0  2  4  5  7  9 11]
True [ 0  2  3  5  7  9 10]
True [ 0  1  3  5  7  8 10]
BachChorales
True [ 0  2  3  5  7  8 10]
False [ 0  2  4  5  7  9 11]
modalChorales
True [ 0  2  3  5  7  8 10]
True [ 0  2  3  5  7  9 10]
True [ 0  2  3  5  7  8 10  0]
True [ 0  1  3  5  7  8 10]
False [ 0  2  4  5  7  9 10]
False [ 0  2  4  5  7  9 11]
False [ 0  2  4  6  7  9 11]


In [29]:
with open('data/idioms_mir_full_info.pickle', 'wb') as f:
    pickle.dump(idioms, f, protocol=pickle.HIGHEST_PROTOCOL)

In [30]:
print(idioms['organum']['[0 2 3 5 7 8 10]']['chords'][0])
print(idioms['organum']['[0 2 3 5 7 8 10]']['gct_transitions'].shape)
print(idioms['organum']['[0 2 3 5 7 8 10]']['mir_eval_transitions'].shape)

{'rpc': array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]), 'prob': 0.07751937984496124, 'gct_array': '[0 0 7]', 'match_idx': 284, 'match_rpc': array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]), 'match_symbol': 'A:5'}
(17, 17)
(348, 348)


In [31]:
# also make a quick reference for transition matrices only
quick_idioms_reference = {}
for idiom_key, idiom_value in idioms.items():
    for mode_key, mode_value in idiom_value.items():
        quick_idioms_reference[ idiom_key + '_' + mode_key ] = mode_value['mir_eval_transitions']

In [32]:
with open('data/idioms_mir_quick_reference.pickle', 'wb') as f:
    pickle.dump(quick_idioms_reference, f, protocol=pickle.HIGHEST_PROTOCOL)